{% set version = "0.9.0" %}

package:
  name: pyhdf
  version: {{ version }}

source:
  url: http://hdfeos.org/software/pyhdf/pyhdf-{{ version }}.tar.gz
  sha256: f1fd2d72838f30fc4e3a7688a4e1a395483b08e54f4955f3b4d384639e13c67a

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - hdf4
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - hdf4

test:
  imports:
    - pyhdf
  commands:
    - conda inspect linkages -p $PREFIX pyhdf  # [not win]
    - conda inspect objects -p $PREFIX pyhdf  # [osx]

about:
  home:  http://hdfeos.org/software/pyhdf
  license: Public Domain
  summary: 'Python interface to the NCSA HDF4 library.'

extra:
  recipe-maintainers:
      - ocefpaf
