{% set version = "0.10.3" %}

package:
  name: pyhdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyhdf/pyhdf-{{ version }}.tar.gz
  sha256: a3b1ba8056e9a44234f00c2c9592b90f569f5af3260ac3e88a8f8ff9374396a8

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - hdf4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf4

test:
  imports:
    - pyhdf

about:
  home: https://github.com/fhs/pyhdf
  license: MIT
  license_file: LICENSE
  summary: Python interface to the NCSA HDF4 library

extra:
  recipe-maintainers:
    - ocefpaf
