{% set version = "0.10.2" %}

package:
  name: pyhdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyhdf/pyhdf-{{ version }}.tar.gz
  sha256: b1cc5e216d8f0ecc8006d2f8d8b6d5a546eacb6a9093d8640b76411a3322fcbc

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - hdf4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf4

test:
  imports:
    - pyhdf

about:
  home:  https://github.com/fhs/pyhdf
  license: MIT
  license_file: LICENSE
  summary: 'Python interface to the NCSA HDF4 library'

extra:
  recipe-maintainers:
      - ocefpaf
