travis:
  secure:
    BINSTAR_TOKEN: NJezwPojkX+6aNUkVkY2htWYZ1ysFjOd+3SZagXKmoFlzLxsm0BWC5p303gNl79V3BMB3yRUtSIIppSbuRQGAE30GGz+EzrxcTb3V+DFNwJbAIqd02E8Xys7IGf6zDJOSGuSxMzFbkaUvC4GrDsttN4rqLGKKGY6k1c3/2iZVOv6LUADyJcZ3JPU0tM4iX2LyfGK5DKnM6Zi/OU+hp/SrrIyB3mEvXRzq7Wq55VLQ89YT9lgTNO56wr4TJRVe9gYwKC2pnMrCdU22ieX6uLF+fv0MreC1gHAZq6d3eqrHUDyxjNx30eF5kl9DkV1lysrWpxMFz6k03xuLhh8edyDl2uQDw0BZ8ECjNQNaQwoBRa7SeT7briDPMyYjwAD1rDP3u2077p6YzfsNso8vadhAHkv/OOXiL/5v72HiZ7qKpHGWHPFdSz58WJDkUTGjOELTqfqqFt56eRnE36MnJLAMwSOv23MBnHJEEYxkEpF8w7Zo0k2XorzdQiGXuCF+iWRbN5GHm5VwNKKIK06XHR3qf6vfR8LDL0u5c1s9TXnsSQgpImu4IbgIWFHsjsN8Pdp/07M4XPn97Sx4ipbxOdiw7/ZtUMqOU0ho2IfsWBQerh+VivtZIfCCq5S5my/1nTBLPkhg0cnB/ja4fcOwfhWz6/iUb1Oj/vlcerGh2e4SO4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
