appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: huo7JXb7l8lt5J8QtBJgX1o+HuIpurjCB93EHrwz7NFT+kb1nTBYUgZht6QB2lVIXjDhTyToQNi/4ma/hfIIJOkGXJzTWNzWQevTyKE0XsLJ7pPowX0YDC/wHoGma4BqvfTc5JCNPuCpUZy/4WJO2l5OgMCaLC5gLiP7pdbbWtyZ57rsfrFsHmwXsUWMBi4wgW+OIJeSmeDEuS0MGMJ/OS2rY29QXX0tCFiEL9zqYD9Ve0CLG0xX5BNtvak4LrxE3gM0NekMSkVc1kN9HAv5wNex6Jf93tCRQ/AVPls8zu/1B8bZwWN2nCOVuZbefJX9wmFzzozcgb3GtE3Hn7MTjT0NXRW0VLAHgigTtzn75O//ZZh5/7XLxucHkReX9gliKauzLnnWPEMMkHoaaV5Z45g/oKK0agaQz2vxz7YcWH6sSvQSCH6gE7Lm3gM0sF961c4BeR+8dSG8HhtK1tp9tgJaqPN7CEjB+LeyDO4W689ISo1FzOOOMtM+BM01UaD1C5ILfZyPupV3o1GSveXT6ZpXRDR3rYC3M+60rCnj6Yymt+TAsXQDrRhJQ+ykYFGFYAoRug1AE9FUtOsaCIwqfMvLhwQe1D/efNfHrIfDPIM4I28OH5/22pmesE0pfxjqEAORLFv/SzAsx0RzCZPrdULylNtn0E+ZCUZYrvZz48I=}
provider:
  win: azure
conda_forge_output_validation: true
