travis:
  secure:
    BINSTAR_TOKEN: KsYjkcW8f8aosJGbwYwgMf/Tixn6rSKutkxLW2mhD2TYoqVK5+n4h3SpCBzhylJClOpqZHs9k0ExrwtYc/8qUdMYrxoeTC0S9bTjvLLpUlFq94gK5NRoHY/JpxH9WZ8niOA0VUtTrRmLoKbSJ66yMD0A0qyC1brmiu1WHEr+asOKs0+9grI9JcyMH8iLnFbIL6A2GHic2fz9natAubF5hptbEXpqUeFTvN7qKKk/2YcR0TSDfAgTjpV4fdXcRadBeYSuO+ArKZMiSFUxof0yVtBRE785HvDKdf2cijdRWJkVpSsxBrE3I0J1hbXDRFP5eV9ks8duvaHz4F9eYe6nlflhn/LWdC9E8dLaW86KdJM37BDzlPOZaCF9TuWKkfXChatbX6EMW4liuQ0YtNfZyHnZ9LO4bUccg206l2XdOlwbK7KJhWDVJCm/ZlyQ2yzSP+In0sX2CxljkEgLBbuQcUSHmX3tuOBWglF6KdUOqCXWn6uJXA4OSyS/rgFQ2bdi1Wkh+E5qacEO1XQiAlI5fNyriOyT6ELM5069na4KxZtkQEpzucx1NfpIMf1gD1sy4Pqm8fM9IL1n19D8n8JCJvEQhg+6V+h4f/A7X/lELaTqd6Yt3sgKAMUGIkqdSIXf67Tx89tzPvrVO5rjo+ca39r/ujncV2bO7sD5lKgNOSw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
